package com.jianma.yxyp.model;
// default package
// Generated 2018-10-31 11:09:19 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SmsMessage generated by hbm2java
 */
public class SmsMessage implements java.io.Serializable {

	private Integer id;
	private String remoteAddress;
	private String remoteHost;
	private String mobile;
	private String code;
	private Date createtime;

	public SmsMessage() {
	}

	public SmsMessage(String remoteAddress, String remoteHost, String mobile, Date createtime) {
		this.remoteAddress = remoteAddress;
		this.remoteHost = remoteHost;
		this.mobile = mobile;
		this.createtime = createtime;
	}

	public SmsMessage(String remoteAddress, String remoteHost, String mobile, String code, Date createtime) {
		this.remoteAddress = remoteAddress;
		this.remoteHost = remoteHost;
		this.mobile = mobile;
		this.code = code;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRemoteAddress() {
		return this.remoteAddress;
	}

	public void setRemoteAddress(String remoteAddress) {
		this.remoteAddress = remoteAddress;
	}

	public String getRemoteHost() {
		return this.remoteHost;
	}

	public void setRemoteHost(String remoteHost) {
		this.remoteHost = remoteHost;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

}
